
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form action="<?php echo BASE; ?>recuperar/solicitar/" class="form-horizontal" method="post">
                      <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail:</label>
                        <div class="col-sm-8">
                          <input type="email" name="email" class="form-control" id="email" placeholder="seuemail@dominio.com.br" value="<?php echo $this->request->post('email') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-success">Enviar link de redefinição</button>
                        </div>
                      </div>
                    </form>
                </div>